[[redirects]]
  from = "/feed/"
  to = "/feed/index.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      default-src 'self';
      style-src-elem 'self' 'unsafe-inline';
      """
