export const propertiesOrder = [
	'all',

	'position',
	'position-anchor',
	'position-area',
	'position-try-fallbacks',
	'position-try-order',
	'position-try',
	'position-visibility',

	'top',
	'right',
	'bottom',
	'left',

	'inset',
	'inset-area',
	'inset-inline',
	'inset-inline-start',
	'inset-inline-end',
	'inset-block',
	'inset-block-start',
	'inset-block-end',

	'anchor-default',
	'anchor-name',
	'anchor-scroll',

	'z-index',

	'display',

	'grid-template',
	'grid-template-rows',
	'grid-template-columns',
	'grid-template-areas',
	'grid-auto-rows',
	'grid-auto-columns',
	'grid-auto-flow',
	'grid',
	'grid-area',
	'grid-row',
	'grid-row-start',
	'grid-row-end',
	'grid-column',
	'grid-column-start',
	'grid-column-end',
	'grid-gap',
	'grid-row-gap',
	'grid-column-gap',

	'flex',
	'flex-grow',
	'flex-shrink',
	'flex-basis',
	'flex-flow',
	'flex-direction',
	'flex-wrap',

	'order',

	'place-content',
	'align-content',
	'justify-content',

	'place-items',
	'align-items',
	'justify-items',

	'place-self',
	'align-self',
	'justify-self',

	'gap',
	'row-gap',
	'column-gap',

	'columns',
	'column-count',
	'column-fill',
	'column-gap',
	'column-rule',
	'column-rule-color',
	'column-rule-style',
	'column-rule-width',
	'column-span',
	'column-width',

	'table-layout',
	'caption-side',
	'empty-cells',

	'float',
	'float-defer',
	'float-offset',
	'float-reference',
	'clear',

	'object-fit',
	'object-position',

	'margin',
	'margin-top',
	'margin-right',
	'margin-bottom',
	'margin-left',

	'margin-inline',
	'margin-inline-start',
	'margin-inline-end',

	'margin-block',
	'margin-block-start',
	'margin-block-end',

	'margin-break',
	'margin-trim',

	'padding',
	'padding-top',
	'padding-right',
	'padding-bottom',
	'padding-left',

	'padding-inline',
	'padding-inline-start',
	'padding-inline-end',

	'padding-block',
	'padding-block-start',
	'padding-block-end',

	'box-sizing',
	'aspect-ratio',

	'width',
	'min-width',
	'max-width',

	'inline-size',
	'min-inline-size',
	'max-inline-size',

	'height',
	'min-height',
	'max-height',

	'block-size',
	'min-block-size',
	'max-block-size',

	'contain',
	'contain-intrinsic-width',
	'contain-intrinsic-height',
	'contain-intrinsic-size',
	'contain-intrinsic-inline-size',
	'contain-intrinsic-block-size',

	'container',
	'container-name',
	'container-type',

	'overflow',
	'overflow-x',
	'overflow-y',
	'overflow-inline',
	'overflow-block',
	'overflow-scrolling',
	'overflow-anchor',
	'overflow-clip-margin',
	'overflow-wrap',

	'clip',
	'clip-path',
	'clip-rule',

	'scroll-behavior',

	'scroll-margin',
	'scroll-margin-top',
	'scroll-margin-right',
	'scroll-margin-bottom',
	'scroll-margin-left',

	'scroll-margin-inline',
	'scroll-margin-inline-start',
	'scroll-margin-inline-end',
	'scroll-margin-block',
	'scroll-margin-block-start',
	'scroll-margin-block-end',

	'scroll-marker-group',

	'scroll-padding',
	'scroll-padding-top',
	'scroll-padding-right',
	'scroll-padding-bottom',
	'scroll-padding-left',

	'scroll-padding-inline',
	'scroll-padding-inline-start',
	'scroll-padding-inline-end',
	'scroll-padding-block',
	'scroll-padding-block-start',
	'scroll-padding-block-end',

	'scroll-snap-type',
	'scroll-snap-align',
	'scroll-snap-stop',

	'scroll-timeline',
	'scroll-timeline-name',
	'scroll-timeline-axis',

	'scrollbar-width',
	'scrollbar-gutter',
	'scrollbar-color',

	'overscroll-behavior',
	'overscroll-behavior-x',
	'overscroll-behavior-y',
	'overscroll-behavior-inline',
	'overscroll-behavior-block',

	'appearance',
	'box-shadow',

	'outline',
	'outline-width',
	'outline-style',
	'outline-color',
	'outline-offset',

	'border',
	'border-width',
	'border-style',
	'border-color',

	'border-top',
	'border-top-width',
	'border-top-style',
	'border-top-color',

	'border-right',
	'border-right-width',
	'border-right-style',
	'border-right-color',

	'border-bottom',
	'border-bottom-width',
	'border-bottom-style',
	'border-bottom-color',

	'border-left',
	'border-left-width',
	'border-left-style',
	'border-left-color',

	'border-inline',
	'border-inline-width',
	'border-inline-style',
	'border-inline-color',

	'border-inline-start',
	'border-inline-start-width',
	'border-inline-start-style',
	'border-inline-start-color',

	'border-inline-end',
	'border-inline-end-width',
	'border-inline-end-style',
	'border-inline-end-color',

	'border-block',
	'border-block-width',
	'border-block-style',
	'border-block-color',
	'border-block-start',

	'border-block-start-width',
	'border-block-start-style',
	'border-block-start-color',

	'border-block-end',
	'border-block-end-width',
	'border-block-end-style',
	'border-block-end-color',

	'border-radius',

	'border-top-left-radius',
	'border-top-right-radius',
	'border-bottom-right-radius',
	'border-bottom-left-radius',

	'border-start-start-radius',
	'border-start-end-radius',
	'border-end-end-radius',
	'border-end-start-radius',

	'border-image',
	'border-image-source',
	'border-image-slice',
	'border-image-width',
	'border-image-outset',
	'border-image-repeat',

	'border-top-image',
	'border-right-image',
	'border-bottom-image',
	'border-left-image',

	'border-top-left-image',
	'border-top-right-image',
	'border-bottom-right-image',
	'border-bottom-left-image',

	'border-corner-image',

	'border-boundary',
	'border-collapse',
	'border-spacing',

	'box-decoration-break',

	'stroke',
	'stroke-dasharray',
	'stroke-dashoffset',
	'stroke-linecap',
	'stroke-linejoin',
	'stroke-miterlimit',
	'stroke-opacity',
	'stroke-width',

	'background',
	'background-color',
	'background-image',
	'background-position',
	'background-position-x',
	'background-position-y',
	'background-size',
	'background-clip',
	'background-origin',
	'background-attachment',
	'background-repeat',
	'background-blend-mode',

	'backface-visibility',

	'fill',
	'fill-opacity',
	'fill-rule',

	'accent-color',
	'caret-color',

	'color',

	'mask',

	'mask-clip',
	'mask-composite',
	'mask-image',
	'mask-mode',
	'mask-origin',
	'mask-position',
	'mask-repeat',
	'mask-size',
	'mask-type',

	'mask-border',
	'mask-border-mode',
	'mask-border-outset',
	'mask-border-repeat',
	'mask-border-slice',
	'mask-border-source',
	'mask-border-width',

	'direction',
	'writing-mode',
	'unicode-bidi',

	'list-style',
	'list-style-position',
	'list-style-type',
	'list-style-image',

	'marker',
	'marker-start',
	'marker-mid',
	'marker-end',

	'vertical-align',

	'text-align',
	'text-align-last',

	'text-decoration',
	'text-decoration-color',
	'text-decoration-line',
	'text-decoration-skip-ink',
	'text-decoration-skip',
	'text-decoration-style',
	'text-decoration-thickness',

	'text-underline-offset',
	'text-underline-position',

	'text-emphasis',
	'text-emphasis-color',
	'text-emphasis-style',
	'text-emphasis-position',

	'text-indent',
	'text-justify',
	'text-outline',
	'text-transform',

	'text-wrap',
	'text-wrap-mode',
	'text-wrap-style',

	'text-overflow',
	'text-overflow-ellipsis',
	'text-overflow-mode',

	'text-shadow',
	'text-anchor',
	'text-box-edge',
	'text-box-trim',
	'text-box',
	'text-combine-upright',
	'text-orientation',
	'text-rendering',
	'text-size-adjust',
	'text-spacing-trim',

	'letter-spacing',

	'white-space',
	'white-space-collapse',

	'word-spacing',
	'word-wrap',
	'word-break',

	'tab-size',

	'hyphens',
	'hyphenate-character',
	'hyphenate-limit-chars',
	'hanging-punctuation',
	'orphans',
	'widows',
	'initial-letter',

	'line-height',
	'line-break',
	'line-clamp',
	'line-height-step',

	'font',
	'font-weight',
	'font-size',
	'font-size-adjust',
	'font-family',
	'font-style',
	'font-effect',
	'font-synthesis',
	'font-synthesis-position',
	'font-synthesis-small-caps',
	'font-synthesis-style',
	'font-synthesis-weight',
	'font-variant',
	'font-variant-alternates',
	'font-variant-caps',
	'font-variant-east-asian',
	'font-variant-emoji',
	'font-variant-ligatures',
	'font-variant-numeric',
	'font-variant-position',
	'font-variation-settings',
	'font-feature-settings',
	'font-language-override',
	'font-optical-sizing',
	'font-palette',
	'font-kerning',
	'font-smooth',

	'quotes',

	'counter-set',
	'counter-increment',
	'counter-reset',

	'transform',
	'transform-box',
	'transform-origin',
	'transform-style',

	'translate',
	'rotate',
	'scale',
	'perspective',
	'perspective-origin',

	'transition',
	'transition-behavior',
	'transition-delay',
	'transition-duration',
	'transition-property',
	'transition-timing-function',

	'animation',
	'animation-composition',
	'animation-delay',
	'animation-direction',
	'animation-duration',
	'animation-fill-mode',
	'animation-iteration-count',
	'animation-name',
	'animation-play-state',
	'animation-range',
	'animation-range-end',
	'animation-range-start',
	'animation-timeline',
	'animation-timing-function',

	'offset',
	'offset-anchor',
	'offset-distance',
	'offset-path',
	'offset-position',
	'offset-rotate',

	'view-timeline-axis',
	'view-timeline-inset',
	'view-timeline-name',
	'view-timeline',
	'view-transition-class',
	'view-transition-name',

	'timeline-scope',

	'x',
	'y',
	'cx',
	'cy',
	'r',
	'rx',
	'ry',
	'd',

	'math-depth',
	'math-shift',
	'math-style',

	'color-scheme',
	'content',
	'opacity',
	'visibility',

	'filter',
	'backdrop-filter',
	'mix-blend-mode',

	'resize',
	'field-sizing',

	'cursor',
	'pointer-events',
	'touch-action',
	'user-select',

	'zoom',
	'max-zoom',
	'min-zoom',
	'user-zoom',

	'orientation',

	'break-before',
	'break-inside',
	'break-after',

	'will-change',
];
