const htmlmin = require('html-minifier-terser');

module.exports = function(window) {
	const content = window.document.getElementById('article-content');

	if (!content) return;

	const iframes = content.querySelectorAll('iframe');

	for (const iframe of iframes) {
		const source = iframe.getAttribute('src');
		const wrapper = window.document.createElement('figure');

		const template = `
			${iframe.outerHTML}
			<figcaption>
				<a class="action" href="${source}" target="_blank">
					Open in the new tab
					<svg class="action__icon" width="24" height="24" aria-hidden="true">
						<use href="/images/icons.svg#external">
					</svg>
				</a>
			</figcaption>
		`;

		wrapper.innerHTML = async () => {
			await htmlmin.minify(
				template, {
					collapseBooleanAttributes: true,
					collapseWhitespace: true,
					decodeEntities: true,
					includeAutoGeneratedTags: false,
					removeComments: true,
				}
			);
		};

		iframe.replaceWith(wrapper);
	}
}
